# Generated by Django 5.2.7 on 2025-10-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_todoitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
