# Generated by Django 5.2.7 on 2025-10-18 11:19
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list", "0004_todoitem_archived"),
    ]

    operations = [
        TrigramExtension(),
    ]
